// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPS_GameMvc.Data;

namespace RPS_GameMvc.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20200925160411_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("RPS_GameMvc.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ComputerPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("Player1PlayerId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("ComputerPlayerId");

                    b.HasIndex("Player1PlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RPS_GameMvc.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RPS_GameMvc.Models.Round", b =>
                {
                    b.Property<int>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ComputerChoice")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("p1Choice")
                        .HasColumnType("int");

                    b.Property<int?>("player1PlayerId")
                        .HasColumnType("int");

                    b.HasKey("RoundId");

                    b.HasIndex("ComputerPlayerId");

                    b.HasIndex("GameId");

                    b.HasIndex("player1PlayerId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("RPS_GameMvc.Models.Game", b =>
                {
                    b.HasOne("RPS_GameMvc.Models.Player", "Computer")
                        .WithMany()
                        .HasForeignKey("ComputerPlayerId");

                    b.HasOne("RPS_GameMvc.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1PlayerId");

                    b.Navigation("Computer");

                    b.Navigation("Player1");
                });

            modelBuilder.Entity("RPS_GameMvc.Models.Round", b =>
                {
                    b.HasOne("RPS_GameMvc.Models.Player", "Computer")
                        .WithMany()
                        .HasForeignKey("ComputerPlayerId");

                    b.HasOne("RPS_GameMvc.Models.Game", null)
                        .WithMany("rounds")
                        .HasForeignKey("GameId");

                    b.HasOne("RPS_GameMvc.Models.Player", "player1")
                        .WithMany()
                        .HasForeignKey("player1PlayerId");

                    b.Navigation("Computer");

                    b.Navigation("player1");
                });

            modelBuilder.Entity("RPS_GameMvc.Models.Game", b =>
                {
                    b.Navigation("rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
